{"rendered": {"description": {"raw": "The homebrew `python` package now refers to python3. Thus it no longer has the `pip2` command, so some gazebo builds are failing:\r\n\r\n~~~\r\n++ brew install python\r\nWarning: python 3.6.4_3 is already installed\r\n++ export PYTHONPATH=/usr/local/lib/python2.7/site-packages:\r\n++ PYTHONPATH=/usr/local/lib/python2.7/site-packages:\r\n++ pip2 install lxml\r\n./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash: line 77:\r\n pip2: command not found\r\n~~~\r\n\r\n* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1422/\r\n* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1423/\r\n\r\nSo switch back to the unversioned version of pip, which is now available again. Also, update `flaky_junit_merge.py` to support python3. Also update the cleanup script to remove python site-packages for all versions.\r\n\r\nTest build:\r\n\r\n:red_circle: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1424\r\n\r\n:red_circle: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1425/\r\n\r\n:yellow_heart: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1426/ but all the gui tests are marked as failures due to a python3 issue\r\n\r\n:grey_question: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1428/ I aborted it early, but the gui tests are working again with a special branch of gazebo\r\n\r\n:blue_circle: https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat5-homebrew-amd64/32\r\n\r\n:blue_circle: https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat4-homebrew-amd64/61\r\n\r\n:red_circle: https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/8/\r\n\r\n:yellow_heart: https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/9/\r\n\r\nfound another python3 issue in the failed gazebo build (fixed in abc3583), and I found an issue with protobuf (reported upstream [here](https://github.com/Homebrew/homebrew-core/issues/24815))", "markup": "markdown", "html": "<p>The homebrew <code>python</code> package now refers to python3. Thus it no longer has the <code>pip2</code> command, so some gazebo builds are failing:</p>\n<div class=\"codehilite\"><pre><span></span>++ brew install python\nWarning: python 3.6.4_3 is already installed\n++ export PYTHONPATH=/usr/local/lib/python2.7/site-packages:\n++ PYTHONPATH=/usr/local/lib/python2.7/site-packages:\n++ pip2 install lxml\n./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash: line 77:\n pip2: command not found\n</pre></div>\n\n\n<ul>\n<li><a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1422/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1422/</a></li>\n<li><a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1423/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1423/</a></li>\n</ul>\n<p>So switch back to the unversioned version of pip, which is now available again. Also, update <code>flaky_junit_merge.py</code> to support python3. Also update the cleanup script to remove python site-packages for all versions.</p>\n<p>Test build:</p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f534.png\" alt=\"\ud83d\udd34\" title=\":red_circle:\" data-emoji-short-name=\":red_circle:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1424\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1424</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f534.png\" alt=\"\ud83d\udd34\" title=\":red_circle:\" data-emoji-short-name=\":red_circle:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1425/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1425/</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f49b.png\" alt=\"\ud83d\udc9b\" title=\":yellow_heart:\" data-emoji-short-name=\":yellow_heart:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1426/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1426/</a> but all the gui tests are marked as failures due to a python3 issue</p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/2754.png\" alt=\"\u2754\" title=\":grey_question:\" data-emoji-short-name=\":grey_question:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1428/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1428/</a> I aborted it early, but the gui tests are working again with a special branch of gazebo</p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f535.png\" alt=\"\ud83d\udd35\" title=\":blue_circle:\" data-emoji-short-name=\":blue_circle:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat5-homebrew-amd64/32\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat5-homebrew-amd64/32</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f535.png\" alt=\"\ud83d\udd35\" title=\":blue_circle:\" data-emoji-short-name=\":blue_circle:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat4-homebrew-amd64/61\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat4-homebrew-amd64/61</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f534.png\" alt=\"\ud83d\udd34\" title=\":red_circle:\" data-emoji-short-name=\":red_circle:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/8/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/8/</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f49b.png\" alt=\"\ud83d\udc9b\" title=\":yellow_heart:\" data-emoji-short-name=\":yellow_heart:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/9/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/9/</a></p>\n<p>found another python3 issue in the failed gazebo build (fixed in <a href=\"#!/osrf/release-tools/commits/abc3583\" rel=\"nofollow\" class=\"ap-connect-link\">abc3583</a>), and I found an issue with protobuf (reported upstream <a data-is-external-link=\"true\" href=\"https://github.com/Homebrew/homebrew-core/issues/24815\" rel=\"nofollow\">here</a>)</p>", "type": "rendered"}, "title": {"raw": "Brew: use python3", "markup": "markdown", "html": "<p>Brew: use python3</p>", "type": "rendered"}}, "type": "pullrequest", "description": "The homebrew `python` package now refers to python3. Thus it no longer has the `pip2` command, so some gazebo builds are failing:\r\n\r\n~~~\r\n++ brew install python\r\nWarning: python 3.6.4_3 is already installed\r\n++ export PYTHONPATH=/usr/local/lib/python2.7/site-packages:\r\n++ PYTHONPATH=/usr/local/lib/python2.7/site-packages:\r\n++ pip2 install lxml\r\n./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash: line 77:\r\n pip2: command not found\r\n~~~\r\n\r\n* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1422/\r\n* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1423/\r\n\r\nSo switch back to the unversioned version of pip, which is now available again. Also, update `flaky_junit_merge.py` to support python3. Also update the cleanup script to remove python site-packages for all versions.\r\n\r\nTest build:\r\n\r\n:red_circle: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1424\r\n\r\n:red_circle: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1425/\r\n\r\n:yellow_heart: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1426/ but all the gui tests are marked as failures due to a python3 issue\r\n\r\n:grey_question: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1428/ I aborted it early, but the gui tests are working again with a special branch of gazebo\r\n\r\n:blue_circle: https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat5-homebrew-amd64/32\r\n\r\n:blue_circle: https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat4-homebrew-amd64/61\r\n\r\n:red_circle: https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/8/\r\n\r\n:yellow_heart: https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/9/\r\n\r\nfound another python3 issue in the failed gazebo build (fixed in abc3583), and I found an issue with protobuf (reported upstream [here](https://github.com/Homebrew/homebrew-core/issues/24815))", "links": {"decline": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/pullrequests/541/decline"}, "diffstat": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/diffstat/osrf/release-tools:7bc7933e953c%0Da409a42b2281?from_pullrequest_id=541"}, "commits": {"href": "data/repositories/osrf/release-tools/pullrequests/541/commits.json"}, "self": {"href": "data/repositories/osrf/release-tools/pullrequests/541.json"}, "comments": {"href": "data/repositories/osrf/release-tools/pullrequests/541/comments_page=1.json"}, "merge": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/pullrequests/541/merge"}, "html": {"href": "#!/osrf/release-tools/pull-requests/541"}, "activity": {"href": "data/repositories/osrf/release-tools/pullrequests/541/activity.json"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/diff/osrf/release-tools:7bc7933e953c%0Da409a42b2281?from_pullrequest_id=541"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/pullrequests/541/approve"}, "statuses": {"href": "data/repositories/osrf/release-tools/pullrequests/541/statuses_page=1.json"}}, "title": "Brew: use python3", "close_source_branch": true, "reviewers": [], "id": 541, "destination": {"commit": {"hash": "a409a42b2281", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/a409a42b2281.json"}, "html": {"href": "#!/osrf/release-tools/commits/a409a42b2281"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "created_on": "2018-03-02T10:50:38.752459+00:00", "summary": {"raw": "The homebrew `python` package now refers to python3. Thus it no longer has the `pip2` command, so some gazebo builds are failing:\r\n\r\n~~~\r\n++ brew install python\r\nWarning: python 3.6.4_3 is already installed\r\n++ export PYTHONPATH=/usr/local/lib/python2.7/site-packages:\r\n++ PYTHONPATH=/usr/local/lib/python2.7/site-packages:\r\n++ pip2 install lxml\r\n./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash: line 77:\r\n pip2: command not found\r\n~~~\r\n\r\n* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1422/\r\n* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1423/\r\n\r\nSo switch back to the unversioned version of pip, which is now available again. Also, update `flaky_junit_merge.py` to support python3. Also update the cleanup script to remove python site-packages for all versions.\r\n\r\nTest build:\r\n\r\n:red_circle: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1424\r\n\r\n:red_circle: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1425/\r\n\r\n:yellow_heart: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1426/ but all the gui tests are marked as failures due to a python3 issue\r\n\r\n:grey_question: https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1428/ I aborted it early, but the gui tests are working again with a special branch of gazebo\r\n\r\n:blue_circle: https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat5-homebrew-amd64/32\r\n\r\n:blue_circle: https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat4-homebrew-amd64/61\r\n\r\n:red_circle: https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/8/\r\n\r\n:yellow_heart: https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/9/\r\n\r\nfound another python3 issue in the failed gazebo build (fixed in abc3583), and I found an issue with protobuf (reported upstream [here](https://github.com/Homebrew/homebrew-core/issues/24815))", "markup": "markdown", "html": "<p>The homebrew <code>python</code> package now refers to python3. Thus it no longer has the <code>pip2</code> command, so some gazebo builds are failing:</p>\n<div class=\"codehilite\"><pre><span></span>++ brew install python\nWarning: python 3.6.4_3 is already installed\n++ export PYTHONPATH=/usr/local/lib/python2.7/site-packages:\n++ PYTHONPATH=/usr/local/lib/python2.7/site-packages:\n++ pip2 install lxml\n./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash: line 77:\n pip2: command not found\n</pre></div>\n\n\n<ul>\n<li><a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1422/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1422/</a></li>\n<li><a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1423/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1423/</a></li>\n</ul>\n<p>So switch back to the unversioned version of pip, which is now available again. Also, update <code>flaky_junit_merge.py</code> to support python3. Also update the cleanup script to remove python site-packages for all versions.</p>\n<p>Test build:</p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f534.png\" alt=\"\ud83d\udd34\" title=\":red_circle:\" data-emoji-short-name=\":red_circle:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1424\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1424</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f534.png\" alt=\"\ud83d\udd34\" title=\":red_circle:\" data-emoji-short-name=\":red_circle:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1425/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1425/</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f49b.png\" alt=\"\ud83d\udc9b\" title=\":yellow_heart:\" data-emoji-short-name=\":yellow_heart:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1426/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1426/</a> but all the gui tests are marked as failures due to a python3 issue</p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/2754.png\" alt=\"\u2754\" title=\":grey_question:\" data-emoji-short-name=\":grey_question:\" /> <a href=\"https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1428/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1428/</a> I aborted it early, but the gui tests are working again with a special branch of gazebo</p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f535.png\" alt=\"\ud83d\udd35\" title=\":blue_circle:\" data-emoji-short-name=\":blue_circle:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat5-homebrew-amd64/32\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat5-homebrew-amd64/32</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f535.png\" alt=\"\ud83d\udd35\" title=\":blue_circle:\" data-emoji-short-name=\":blue_circle:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat4-homebrew-amd64/61\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/sdformat-ci-sdformat4-homebrew-amd64/61</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f534.png\" alt=\"\ud83d\udd34\" title=\":red_circle:\" data-emoji-short-name=\":red_circle:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/8/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/8/</a></p>\n<p><img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f49b.png\" alt=\"\ud83d\udc9b\" title=\":yellow_heart:\" data-emoji-short-name=\":yellow_heart:\" /> <a href=\"https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/9/\" rel=\"nofollow\" class=\"ap-connect-link\">https://build.osrfoundation.org/view/os_homebrew/job/ignition_transport-ci-ign-transport3-homebrew-amd64/9/</a></p>\n<p>found another python3 issue in the failed gazebo build (fixed in <a href=\"#!/osrf/release-tools/commits/abc3583\" rel=\"nofollow\" class=\"ap-connect-link\">abc3583</a>), and I found an issue with protobuf (reported upstream <a data-is-external-link=\"true\" href=\"https://github.com/Homebrew/homebrew-core/issues/24815\" rel=\"nofollow\">here</a>)</p>", "type": "rendered"}, "source": {"commit": {"hash": "508b45d81e82", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/508b45d81e82.json"}, "html": {"href": "#!/osrf/release-tools/commits/508b45d81e82"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "brew_python3"}}, "comment_count": 3, "state": "MERGED", "task_count": 0, "participants": [{"role": "PARTICIPANT", "participated_on": "2018-03-05T08:58:23.916799+00:00", "type": "participant", "approved": true, "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}}], "reason": "", "updated_on": "2018-03-05T08:58:34.225102+00:00", "author": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "merge_commit": {"hash": "7bc7933e953c", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/7bc7933e953c.json"}, "html": {"href": "#!/osrf/release-tools/commits/7bc7933e953c"}}}, "closed_by": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}}