{"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/96666079.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-96666079"}}, "parent": {"id": 96483725, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/96483725.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-96483725"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "we don\u2019t have too many, ariac is one of the few examples [https://bitbucket.org/osrf/ariac](https://bitbucket.org/osrf/ariac/src/master/)", "markup": "markdown", "html": "<p>we don\u2019t have too many, ariac is one of the few examples <a data-is-external-link=\"true\" href=\"https://bitbucket.org/osrf/ariac/src/master/\" rel=\"nofollow\">https://bitbucket.org/osrf/ariac</a></p>", "type": "rendered"}, "created_on": "2019-03-27T23:05:55.887166+00:00", "user": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "updated_on": "2019-03-27T23:05:55.895001+00:00", "type": "pullrequest_comment", "id": 96666079}