{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "links": {"attachments": {"href": "data/repositories/osrf/release-tools/issues/156/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/release-tools/issues/156.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/issues/156/watch"}, "comments": {"href": "data/repositories/osrf/release-tools/issues/156/comments_page=1.json"}, "html": {"href": "#!/osrf/release-tools/issues/156/flaky_junit_mergepy-missing-lxml"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/issues/156/vote"}}, "reporter": {"display_name": "Tully Foote", "uuid": "{3d90dbd4-b845-466f-b5bd-068566f7ff50}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D"}, "html": {"href": "https://bitbucket.org/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3bc6528f8fe1fef6b6ecc7312ee0cf04d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsTF-2.png"}}, "nickname": "Tully Foote", "type": "user", "account_id": "557058:e2bf789f-2138-4a4e-ba39-3d618078e20b"}, "title": "flaky_junit_merge.py missing lxml", "component": {"name": "docker", "links": {"self": {"href": "data/repositories/osrf/release-tools/components/399531.json"}}}, "votes": 0, "watches": 1, "content": {"raw": "This is likely due to [#!/osrf/release-tools/pull-requests/948](#!/osrf/release-tools/pull-requests/948)\r\n\r\nIt appears to be being run inside the container. I think the appropriate fix is to change the shebang to be \\`#!/usr/bin/env python3\\` as it looks to be called inside the container which has switched to python3 but before doing that I want to understand where else it might be called.", "markup": "markdown", "html": "<p>This is likely due to <a data-is-external-link=\"true\" href=\"#!/osrf/release-tools/pull-requests/948\" rel=\"nofollow\">#!/osrf/release-tools/pull-requests/948</a></p>\n<p>It appears to be being run inside the container. I think the appropriate fix is to change the shebang to be `#!/usr/bin/env python3` as it looks to be called inside the container which has switched to python3 but before doing that I want to understand where else it might be called.</p>", "type": "rendered"}, "assignee": {"display_name": "Tully Foote", "uuid": "{3d90dbd4-b845-466f-b5bd-068566f7ff50}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D"}, "html": {"href": "https://bitbucket.org/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3bc6528f8fe1fef6b6ecc7312ee0cf04d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsTF-2.png"}}, "nickname": "Tully Foote", "type": "user", "account_id": "557058:e2bf789f-2138-4a4e-ba39-3d618078e20b"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2020-03-03T04:46:53.714148+00:00", "milestone": null, "updated_on": "2020-03-04T21:49:04.226221+00:00", "type": "issue", "id": 156}